apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: userdata
spec:
  secretRef: 
    name: fake-secret
  details:
    dataFormat: parquet
    connection:
      name: https
      https:
        url: "https://github.com/Teradata/kylo/raw/master/samples/sample-data/parquet/userdata2.parquet"
  metadata:
    name: test data
    geography: theshire 
    tags:
      Purpose.finance: true
    columns:
      - name: first_name
        tags:
          PII.Sensitive: true
      - name: last_name
        tags:
          PII.Sensitive: true
      - name: email
        tags:
          PII.Sensitive: true
      - name: birthdate
        tags:
          PII.Sensitive: true
