apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: userdata
spec:
  secretRef: 
    name: fake-secret
  details:
    dataFormat: json
    connection:
      name: localfile
      localfile:
        destination_path: airbyte_out
  metadata:
    name: test data
    geography: theshire 
    tags:
      Purpose.finance: true
    columns:
      - name: DOB
        tags:
          PII.Sensitive: true
      - name: FirstName
        tags:
          PII.Sensitive: true
      - name: LastNAME
        tags:
          PII.Sensitive: true
