apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: userdata
spec:
  secretRef: 
    name: fake-secret
  details:
    dataFormat: csv
    connection:
      name: file
      file:
        connector: airbyte/destination-local-json
        destination_path: airbyte_out
  metadata:
    name: test data
    geography: theshire 
    tags:
      finance: true
    columns:
      - name: first_name
        tags:
          PII: true
      - name: last_name
        tags:
          PII: true
      - name: email
        tags:
          PII: true
      - name: birthdate
        tags:
          PII: true
