apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: airbyte-module
  labels:
    name: airbyte-module
    version: latest # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/airbyte-module-chart:0.0.0-main
    values:
      image.tag: 0.0.0
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: "80"
            scheme: grpc
      supportedInterfaces:
        - source:
            protocol: postgres
            dataformat: csv
        - source:
            protocol: mysql
            dataformat: csv
        - source:
            protocol: google-sheets
            dataformat: csv
        - source:
            protocol: us-census
            dataformat: csv
        - source:
            protocol: file
            dataformat: csv

