app-uuid: {{ .Values.uuid | default "app-uuid-missing" }}
{{ if .Values.assets -}}
data:
{{- $connectorsMap := .Values.connectors }}
{{- range $asset := .Values.assets }}
  - name: {{  $asset.assetID }}
    {{- $operation := $asset.capability }}
    {{- if and (.args) (eq (len .args) 1) -}}
       {{- with (index .args 0) }}
         {{- $connectionName := .connection.name }}
         {{- $connectionDetails := get .connection .connection.name }}
         {{- if hasKey $connectorsMap $connectionName }}
            {{- $additionalPropertiesForConnector := get $connectorsMap $connectionName }}
            {{- if hasKey $additionalPropertiesForConnector $operation }}
              {{- $additionalPropertiesForConnectorOp := get $additionalPropertiesForConnector $operation }}
              {{- $connectionDetails := mergeOverwrite $connectionDetails $additionalPropertiesForConnectorOp }}
                 {{ print "connection:" | nindent 4 }}
                 {{- .connection | toYaml | nindent 6 }}
            {{- else }}
              {{- toYaml . | nindent 4 }}
            {{- end }}
         {{- else }}
            {{- toYaml . | nindent 4 }}
         {{- end }}
       {{- end }}
    {{- end }}
{{- end }}
{{- else -}}
data: []
{{- end -}}
