# Try it with `helm install --generate-name --dry-run -f helm/abm/values.sample.yaml helm/abm`
labels:
  name: 012d42539692bba841a7
  namespace: default
uuid: "12345678"
assets:
- args:
  - connection:
        name: mysql
        mysql:
          database: test
          host: host.docker.internal
          port: 3306
  assetID: new-data-parquet
  capability: read


