# Try it with `helm install --generate-name --dry-run -f helm/abm/values.sample.yaml helm/abm`
labels:
  name: 012d42539692bba841a7
  namespace: default
uuid: "12345678"
assets:
- args:
  - connection:
      name: https
      https:
        url: "https://github.com/Teradata/kylo/raw/master/samples/sample-data/parquet/userdata2.parquet"
    format: parquet
    vault:
      write:
        address: http://vault.fybrik-system:8200
        authPath: /v1/auth/kubernetes/login
        role: module
        secretPath: /v1/kubernetes-secrets/bucket-creds?namespace=fybrik-system
  assetID: new-data-parquet
  capability: read
  assetID: "userdata"
