# Default values for airbyte-module.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/fybrik/airbyte-module
  tag: main
  pullPolicy: null
  pullSecret: null

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Additional connection properties that should be passed to
# the Airbyte connector. If such exists, they are merged with the
# connection properties defined in Fybrik taxonomy to configure
# the Airbyte connector. Otherwise only the connection properties 
# defined in Fybrik taxonomy are used to configure the Airbyte connector.
connectors:
  mysql:
    # Specify properties for source.
    read:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/main/resources/spec.json
      replication_method:
        method: "STANDARD"
      connector: airbyte/source-mysql
    # Specify properties for destination.
    write:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-mysql/src/main/resources/spec.json
      connector: airbyte/destination-mysql
  google-sheets:
    # Specify properties for source.
    read:
      # https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/spec.yaml
      connector: airbyte/source-google-sheets
    # Specify properties for destination.
    write:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-google-sheets/destination_google_sheets/spec.json
      connector: airbyte/destination-google-sheets
  postgres:
      # Specify properties for source.
      read:
         # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/resources/spec.json
         connector: airbyte/source-postgres
      write:
        # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-postgres/src/main/resources/spec.json
        connector: airbyte/destination-postgres
        # The default schema tables are written to if the source does not specify a namespace. The usual value for this field is "public".
        schema: public

